// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Project.Models
{
    public partial class Favourit
    {
        [Key]
        public int ProductID { get; set; }
        [Key]
        public string UserID { get; set; }

        [ForeignKey(nameof(ProductID))]
        [InverseProperty("Favourits")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(UserID))]
        [InverseProperty(nameof(AspNetUser.Favourits))]
        public virtual AspNetUser User { get; set; }
    }
}